-- MySQL Script generated by MySQL Workbench
-- Wed Sep  4 10:57:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BSAGP
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BSAGP` ;

-- -----------------------------------------------------
-- Schema BSAGP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BSAGP` DEFAULT CHARACTER SET utf8 ;
USE `BSAGP` ;

-- -----------------------------------------------------
-- Table `BSAGP`.`Produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BSAGP`.`Produtos` ;

CREATE TABLE IF NOT EXISTS `BSAGP`.`Produtos` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(20) NOT NULL,
  `preco` DECIMAL(2) NOT NULL,
  `quantidade_estoque` INT NOT NULL,
  `categoria` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BSAGP`.`Promocoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BSAGP`.`Promocoes` ;

CREATE TABLE IF NOT EXISTS `BSAGP`.`Promocoes` (
  `id_promocao` INT NOT NULL AUTO_INCREMENT,
  `desconto` DECIMAL(2) NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_termino` DATE NOT NULL,
  PRIMARY KEY (`id_promocao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BSAGP`.`Funcionarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BSAGP`.`Funcionarios` ;

CREATE TABLE IF NOT EXISTS `BSAGP`.`Funcionarios` (
  `id_funcionario` INT NOT NULL,
  `nome_funcionario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BSAGP`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BSAGP`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `BSAGP`.`Clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(45) NOT NULL,
  `cpf_cliente` INT NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BSAGP`.`Vendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BSAGP`.`Vendas` ;

CREATE TABLE IF NOT EXISTS `BSAGP`.`Vendas` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `id_funcionario` INT NOT NULL,
  `id_cliente` INT NULL,
  `metodo_pagamento` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_Vendas_Funcionarios1_idx` (`id_funcionario` ASC) VISIBLE,
  INDEX `fk_Vendas_Clientes1_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Vendas_Funcionarios1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `BSAGP`.`Funcionarios` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendas_Clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `BSAGP`.`Clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BSAGP`.`Carrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BSAGP`.`Carrinho` ;

CREATE TABLE IF NOT EXISTS `BSAGP`.`Carrinho` (
  `id_carrinho` INT NOT NULL AUTO_INCREMENT,
  `id_produto` INT NOT NULL,
  `id_venda` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id_carrinho`),
  INDEX `fk_Produtos_has_Vendas_Vendas1_idx` (`id_venda` ASC) VISIBLE,
  INDEX `fk_Produtos_has_Vendas_Produtos_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_Produtos_has_Vendas_Produtos`
    FOREIGN KEY (`id_produto`)
    REFERENCES `BSAGP`.`Produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_has_Vendas_Vendas1`
    FOREIGN KEY (`id_venda`)
    REFERENCES `BSAGP`.`Vendas` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BSAGP`.`Produtos_Promocao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BSAGP`.`Produtos_Promocao` ;

CREATE TABLE IF NOT EXISTS `BSAGP`.`Produtos_Promocao` (
  `id_produtos_promocao` INT NOT NULL AUTO_INCREMENT,
  `id_produto` INT NOT NULL,
  `id_promocao` INT NOT NULL,
  PRIMARY KEY (`id_produtos_promocao`),
  INDEX `fk_Produtos_has_Promocoes_Promocoes1_idx` (`id_promocao` ASC) VISIBLE,
  INDEX `fk_Produtos_has_Promocoes_Produtos1_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_Produtos_has_Promocoes_Produtos1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `BSAGP`.`Produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_has_Promocoes_Promocoes1`
    FOREIGN KEY (`id_promocao`)
    REFERENCES `BSAGP`.`Promocoes` (`id_promocao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
